# Generated by Django 2.1.5 on 2019-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=25, verbose_name='Başlık')),
                ('checked', models.BooleanField(verbose_name='Durum')),
            ],
        ),
    ]
